'use strict';const $=id=>document.getElementById(id);let epoch=0,last=null;
function clear(){epoch++;last=null;$('result').hidden=true;$('error').textContent=''}
for(const id of ['old','new'])$(id).onchange=()=>{clear();$('scope').checked=false};$('scope').onchange=clear;
const names={earned:'受取手数料前の計算収益',received:'実入金の入力額',payoutFees:'受取手数料',remaining:'計算上の未回収',paidCosts:'支払済み費用',cashResult:'確認済み費用を引いた現金差額'};
function fmt(n,c){return n===null?'不明':FinanceDesk.format(n,c)}
$('form').onsubmit=async e=>{e.preventDefault();clear();const t=epoch;try{const files=[$('old').files[0],$('new').files[0]];if(files.some(f=>!f||f.size>1000000))throw Error('訂正前と訂正後の入力JSONを各1MB以内で選んでください。');const values=await Promise.all(files.map(async f=>RevisionCheck.parse(new TextDecoder('utf-8',{fatal:true}).decode(await f.arrayBuffer()))));if(t!==epoch)return;last=RevisionCheck.compare(values[0],values[1],$('scope').checked);$('report').textContent=(last.kind==='example'?'架空の比較':'自分の入力値の比較（着金の証明ではありません）')+' / '+last.period+'\n\n'+last.rows.map(r=>r.currency+' / '+names[r.field]+'\n'+fmt(r.before,r.currency)+' → '+fmt(r.after,r.currency)+' / 差分 '+fmt(r.delta,r.currency)+' / '+r.state).join('\n\n')+'\n\n'+[...last.paths,...last.warnings].join('\n');let contextNode=$('context');if(!contextNode){contextNode=document.createElement('p');contextNode.id='context';$('cards').before(contextNode);}contextNode.textContent=(last.kind==='example'?'架空入力の比較':'本人入力の比較・着金の証明ではありません')+' / '+last.period;renderCards(last);$('result').hidden=false}catch(err){if(t===epoch){last=null;$('error').textContent=err.message}}};
function save(name,text,type){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}$('txt').onclick=()=>{if(last)save('income-revision-review.txt',$('report').textContent,'text/plain;charset=utf-8')};$('csv').onclick=()=>{if(last)save('income-revision-comparison.csv',FinanceDesk.csv([['data_kind','period','currency','item','before','after','difference','state'],...last.rows.map(r=>[last.kind,last.period,r.currency,names[r.field],r.before===null?'':r.before/FinanceDesk.factors[r.currency],r.after===null?'':r.after/FinanceDesk.factors[r.currency],r.delta===null?'':r.delta/FinanceDesk.factors[r.currency],r.state])]),'text/csv;charset=utf-8')};

function renderCards(r){const root=$('cards');root.replaceChildren();for(const currency of ['JPY','USD']){const rows=r.rows.filter(x=>x.currency===currency);if(!rows.length)continue;const group=document.createElement('div'),title=document.createElement('h3');title.textContent=currency;group.append(title);const grid=document.createElement('div');grid.className='metrics';for(const row of rows){const card=document.createElement('div');card.className='metric'+(row.delta===null?' unknown':'');const h=document.createElement('h3');h.textContent=names[row.field];card.append(h);const dl=document.createElement('dl');for(const [label,value] of [['訂正前',row.before],['訂正後',row.after],['差分',row.delta]]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=fmt(value,currency);dl.append(dt,dd)}const state=document.createElement('p');state.textContent=row.state;card.append(dl,state);grid.append(card)}group.append(grid);root.append(group)}}
