const $=id=>document.getElementById(id);function saveText(name,text,type='text/plain;charset=utf-8'){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}function clearResult(){if($('result'))$('result').hidden=true;if($('buy'))$('buy').hidden=true}

const columns=["row", "period", "name", "type", "currency", "basis", "amount", "refunds", "platformFees", "received", "payoutFees", "costPaid", "costComplete"];let rows=[],csvOut='',epoch=0;
function parseCSV(text){text=text.replace(/^\uFEFF/,'');const rows=[];let row=[],cell='',quoted=false,after=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'){if(text[i+1]==='"'){cell+='"';i++}else{quoted=false;after=true}}else cell+=c;continue}if(after&&![',','\n','\r'].includes(c))throw Error('閉じた引用符の後に不正な文字');if(c==='"'){if(cell||after)throw Error('引用符の位置が不正');quoted=true}else if(c===','){row.push(cell);cell='';after=false}else if(c==='\n'||c==='\r'){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);rows.push(row);row=[];cell='';after=false}else cell+=c}if(quoted)throw Error('引用符が閉じていません');if(row.length||cell||after){row.push(cell);rows.push(row)}if(!rows.length)throw Error('CSVが空です');if(rows.length<2)throw Error('データ行がありません');if(rows.length>5001)throw Error('5000行までです');const h=rows[0];if(h.some(x=>!x.trim())||new Set(h).size!==h.length)throw Error('空欄・重複ヘッダーを直してください');if(rows.some(x=>x.length!==h.length))throw Error('列数が一致しない行があります');return rows}
function encodeCSV(rows){return rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n')+'\r\n'}
function invalidate(){epoch++;clearResult();$('form').hidden=true;rows=[];$('error').textContent=''}$('csv').oninput=invalidate;$('file').onchange=async()=>{invalidate();const token=epoch;const f=$('file').files[0];if(!f)return;if(f.size>1000000){$('error').textContent='1MBまでです';return}try{const text=new TextDecoder('utf-8',{fatal:true}).decode(await f.arrayBuffer());if(token!==epoch)return;$('csv').value=text}catch{$('error').textContent='UTF-8で保存したCSVが必要です'}};$('example').onclick=()=>{invalidate();$('csv').value='区分,対象月,商品,通貨,売上\nincome,2026-10,架空の作品,JPY,500\n'};
$('load').onclick=()=>{clearResult();try{if($('csv').value.length>1000000)throw Error('1MBまでです');rows=parseCSV($('csv').value);$('mapping').replaceChildren();for(const col of columns){const label=document.createElement('label');label.textContent=col+(['row','period','currency'].includes(col)?'（対応必須）':'');const select=document.createElement('select');select.dataset.col=col;select.append(new Option('対応なし・値は不明',''));rows[0].forEach((h,i)=>select.append(new Option(h,String(i))));const match=rows[0].indexOf(col);if(match>=0)select.value=String(match);select.onchange=clearResult;label.append(select);$('mapping').append(label)}$('form').hidden=false;$('error').textContent=''}catch(e){rows=[];$('form').hidden=true;$('error').textContent=e.message}};
$('form').onsubmit=e=>{e.preventDefault();clearResult();const selects=[...$('mapping').querySelectorAll('select')],maps=selects.map(x=>x.value===''?null:Number(x.value));try{for(const col of ['row','period','currency'])if(maps[columns.indexOf(col)]===null)throw Error(col+'の対応を選んでください');const used=maps.filter(x=>x!==null);if(new Set(used).size!==used.length)throw Error('同じ元列を複数の意味へ対応させられません');const output=rows.slice(1).map(r=>maps.map((i,n)=>{let v=i===null?'':r[i];if(columns[n]==='name'&&/^[\s]*[=+\-@]/.test(v))v="'"+v;return v}));for(const r of output){for(let n=6;n<=11;n++)if(r[n]&&!/^\d+(\.\d+)?$/.test(r[n]))throw Error(columns[n]+'は空欄または非負の小数形式にしてください（桁区切り・式なし）');if(!['income','cost'].includes(r[0]))throw Error('row値はincome/costにしてください');if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(r[1]))throw Error('periodはYYYY-MM形式にしてください');if(!['JPY','USD'].includes(r[4]))throw Error('currency値はJPY/USDにしてください');if(r[3]&&!['sale','membership','referral','reading','other'].includes(r[3]))throw Error('type値が仕様に合いません');if(r[5]&&!['gross','net'].includes(r[5]))throw Error('basis値が仕様に合いません');if(r[12]&&!['true','false'].includes(r[12]))throw Error('costComplete値が仕様に合いません')}
csvOut=encodeCSV([columns,...output]);$('report').textContent=output.length+'行 / 13列。未対応は空欄。\nこれは整形だけです。金額の意味・空欄の理由・値の適合を集計前に自分で確認してください。';$('result').hidden=false;$('error').textContent=''}catch(e){$('error').textContent=e.message}};$('download').onclick=()=>saveText('mapped-income.csv',csvOut,'text/csv;charset=utf-8');
