const $=id=>document.getElementById(id);function saveText(name,text,type='text/plain;charset=utf-8'){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}function clearResult(){if($('result'))$('result').hidden=true;if($('buy'))$('buy').hidden=true}

const columns=["row", "period", "name", "type", "currency", "basis", "amount", "refunds", "platformFees", "received", "payoutFees", "costPaid", "costComplete"];let rows=[],csvOut='',epoch=0;
function parseCSV(text){text=text.replace(/^\uFEFF/,'');const rows=[];let row=[],cell='',quoted=false,after=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'){if(text[i+1]==='"'){cell+='"';i++}else{quoted=false;after=true}}else cell+=c;continue}if(after&&![',','\n','\r'].includes(c))throw Error('Invalid text after a closing quote');if(c==='"'){if(cell||after)throw Error('Invalid quote position');quoted=true}else if(c===','){row.push(cell);cell='';after=false}else if(c==='\n'||c==='\r'){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);rows.push(row);row=[];cell='';after=false}else cell+=c}if(quoted)throw Error('Unclosed quoted field');if(row.length||cell||after){row.push(cell);rows.push(row)}if(!rows.length)throw Error('CSV is empty');if(rows.length<2)throw Error('No data rows');if(rows.length>5001)throw Error('At most 5000 rows');const h=rows[0];if(h.some(x=>!x.trim())||new Set(h).size!==h.length)throw Error('Fix empty or duplicate headers');if(rows.some(x=>x.length!==h.length))throw Error('A row has a different number of columns');return rows}
function encodeCSV(rows){return rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n')+'\r\n'}
function invalidate(){epoch++;clearResult();$('form').hidden=true;rows=[];$('error').textContent=''}$('csv').oninput=invalidate;$('file').onchange=async()=>{invalidate();const token=epoch;const f=$('file').files[0];if(!f)return;if(f.size>1000000){$('error').textContent='At most 1MB';return}try{const text=new TextDecoder('utf-8',{fatal:true}).decode(await f.arrayBuffer());if(token!==epoch)return;$('csv').value=text}catch{$('error').textContent='Use a UTF-8 CSV'}};$('example').onclick=()=>{invalidate();$('csv').value='row,period,name,currency,amount\nincome,2026-10,Fictional work,JPY,500\n'};
$('load').onclick=()=>{clearResult();try{if($('csv').value.length>1000000)throw Error('At most 1MB');rows=parseCSV($('csv').value);$('mapping').replaceChildren();for(const col of columns){const label=document.createElement('label');label.textContent=col+(['row','period','currency'].includes(col)?' (required mapping)':'');const select=document.createElement('select');select.dataset.col=col;select.append(new Option('Not mapped; unknown',''));rows[0].forEach((h,i)=>select.append(new Option(h,String(i))));const match=rows[0].indexOf(col);if(match>=0)select.value=String(match);select.onchange=clearResult;label.append(select);$('mapping').append(label)}$('form').hidden=false;$('error').textContent=''}catch(e){rows=[];$('form').hidden=true;$('error').textContent=e.message}};
$('form').onsubmit=e=>{e.preventDefault();clearResult();const selects=[...$('mapping').querySelectorAll('select')],maps=selects.map(x=>x.value===''?null:Number(x.value));try{for(const col of ['row','period','currency'])if(maps[columns.indexOf(col)]===null)throw Error(col+' needs a mapping');const used=maps.filter(x=>x!==null);if(new Set(used).size!==used.length)throw Error('One source column cannot represent multiple meanings');const output=rows.slice(1).map(r=>maps.map((i,n)=>{let v=i===null?'':r[i];if(columns[n]==='name'&&/^[\s]*[=+\-@]/.test(v))v="'"+v;return v}));for(const r of output){for(let n=6;n<=11;n++)if(r[n]&&!/^\d+(\.\d+)?$/.test(r[n]))throw Error(columns[n]+' must be blank or a nonnegative plain number (no formulas or separators)');if(!['income','cost'].includes(r[0]))throw Error('row must be income/cost');if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(r[1]))throw Error('period must be YYYY-MM');if(!['JPY','USD'].includes(r[4]))throw Error('currency must be JPY/USD');if(r[3]&&!['sale','membership','referral','reading','other'].includes(r[3]))throw Error('Invalid type');if(r[5]&&!['gross','net'].includes(r[5]))throw Error('Invalid basis');if(r[12]&&!['true','false'].includes(r[12]))throw Error('costComplete must be true/false')}
csvOut=encodeCSV([columns,...output]);$('report').textContent=output.length+' rows / 13 columns. Unmapped values are blank.\nMapping only. Verify amount meanings, reasons for blanks and valid values before calculating.';$('result').hidden=false;$('error').textContent=''}catch(e){$('error').textContent=e.message}};$('download').onclick=()=>saveText('mapped-income.csv',csvOut,'text/csv;charset=utf-8');
