'use strict';
function startIncomeMapping(en){
const $=id=>document.getElementById(id),M=IncomeMapping;let rows=[],csvOut='',epoch=0;
const t=(ja,english)=>en?english:ja;
const errors={validation:t('集計前に次の入力を修正してください。','Fix these inputs before calculating.'),headers:t('空欄・重複・曖昧なヘッダーを直してください（大文字小文字・前後空白の違いも重複扱い）。','Fix blank, duplicate or ambiguous headers (case and outer whitespace differences also count).'),quotes:t('CSVの引用符が不正です。','Invalid CSV quoting.'),rows:t('データは1〜5000行です。','Use 1–5000 data rows.'),width:t('列数が一致しない行があります。','A row has a different number of columns.'),recipe:t('対応レシピの形式・キーが不正です。','Invalid recipe format or keys.'),recipeSize:t('レシピは32KB以内です。','Recipe must be at most 32KB.'),missing:t('レシピの元ヘッダーが今回のCSVにありません。','A recipe source header is missing from this CSV.'),duplicate:t('同じ元列を複数の意味へ対応させられません。','One source column cannot represent multiple meanings.'),conflict:t('列対応と定数を同時に指定できません。','Choose a source column or a constant, not both.'),constantConfirm:t('定数の値と、今回のファイル全体に適用する確認が必要です。','Confirm each constant applies to every row in this file.'),meanings:t('金額・返金・手数料・入金の意味を原レポートで確認してください。','Confirm amount, refund, fee and receipt meanings in the source report.'),period:t('対象月はYYYY-MMで明示してください。','Specify the reporting month as YYYY-MM.'),netFees:t('netは返金・販売手数料控除後です。返金・販売手数料列を空欄にして原レポートの意味を再確認してください。','For net amounts, leave refund/platform-fee columns blank and recheck the source meaning.'),constants:t('定数のキーが不正です。','Invalid constant keys.')};
function show(e){$('error').textContent=errors[e.message]||e.message;if(e.details)$('error').textContent+='\n'+e.details.join('\n');}
function save(name,text,type){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function clear(){epoch++;csvOut='';$('result').hidden=true;}
function invalidate(){epoch++;clear();rows=[];$('form').hidden=true;$('error').textContent='';}
function mapping(){return Object.fromEntries(M.columns.map(c=>[c,$('map-'+c).value||null]));}
function resetConstants(){for(const c of Object.keys(M.constants)){$('constant-'+c).value='';$('confirm-'+c).checked=false;}$('meanings-confirm').checked=false;}
function update(c){const mapped=$('map-'+c).value!=='';if(M.constants[c]!==undefined){$('constant-'+c).disabled=mapped;$('confirm-'+c).disabled=mapped;if(mapped){$('constant-'+c).value='';$('confirm-'+c).checked=false;}}clear();$('meanings-confirm').checked=false;}
function render(){ $('mapping').replaceChildren();for(const c of M.columns){const box=document.createElement('fieldset'),legend=document.createElement('legend');legend.textContent=c;box.append(legend);const label=document.createElement('label');label.textContent=t('元CSVの列','Source CSV column');const s=document.createElement('select');s.id='map-'+c;s.append(new Option(t('対応なし・値は不明','Not mapped; unknown'),''));rows[0].forEach(h=>s.append(new Option(h,h)));if(rows[0].includes(c))s.value=c;label.append(s);box.append(label);s.onchange=()=>update(c);
 if(Object.hasOwn(M.constants,c)){const lab=document.createElement('label');lab.textContent=t('または今回のファイル全体の定数','Or a constant for this entire file');let input;if(c==='period'){input=document.createElement('input');input.type='month';}else{input=document.createElement('select');input.append(new Option(t('未指定・不明','Unspecified; unknown'),''));M.constants[c].forEach(v=>input.append(new Option(v,v)));}input.id='constant-'+c;lab.append(input);box.append(lab);const confirm=document.createElement('label'),ch=document.createElement('input');ch.type='checkbox';ch.id='confirm-'+c;confirm.append(ch,document.createTextNode(t(' 今回の全行に適用することを確認した',' Confirmed for every row in this file')));box.append(confirm);input.oninput=()=>{ch.checked=false;clear();$('meanings-confirm').checked=false;};ch.onchange=clear;} $('mapping').append(box);update(c);}}
$('csv').oninput=invalidate;$('file').onchange=async()=>{invalidate();const token=epoch,f=$('file').files[0];if(!f)return;try{if(f.size>1000000)throw Error(t('1MBまでです。','At most 1MB.'));const text=new TextDecoder('utf-8',{fatal:true}).decode(await f.arrayBuffer());if(token===epoch)$('csv').value=text;}catch(e){if(token===epoch)show(e);}};
$('example').onclick=()=>{invalidate();$('csv').value=en?'item,total\nFictional work,500\n':'商品,報告額\n架空の作品,500\n';};
$('load').onclick=()=>{clear();try{if(new TextEncoder().encode($('csv').value).length>1000000)throw Error(t('1MBまでです。','At most 1MB.'));const candidate=M.parseCSV($('csv').value);epoch++;rows=candidate;render();$('form').hidden=false;$('error').textContent='';}catch(e){rows=[];$('form').hidden=true;show(e);}};
$('form').onsubmit=e=>{e.preventDefault();clear();try{const values={},confirm={meanings:$('meanings-confirm').checked};for(const c of Object.keys(M.constants)){values[c]=$('constant-'+c).value;confirm[c]=$('confirm-'+c).checked;}const out=M.convert(rows,mapping(),values,confirm,validateCSV);csvOut=out.csv;$('report').textContent=out.count+t('行 / 13列。未指定は空欄のままです。',' rows / 13 columns. Unspecified values remain blank.')+(out.income?t('保存したCSVを次の無料集計へ読み込めます。',' Load this saved CSV into the free trial.'):t('費用のみのCSVです。無料集計には同じ期間の収入行と合わせたCSVが必要です。一括キットでは同じ期間の収入CSVと一緒に指定してください。',' This file contains costs only. The free trial needs income rows in the same CSV. In the batch kit, provide this together with an income CSV for the same period.'));$('result').hidden=false;$('error').textContent='';}catch(e){show(e);}};
$('download').onclick=()=>{if(csvOut)save('mapped-income.csv',csvOut,'text/csv;charset=utf-8');};
$('recipe-save').onclick=()=>{try{const r=M.recipe(mapping(),rows[0]);save('income-column-recipe.json',JSON.stringify(r,null,2)+'\n','application/json');$('error').textContent=t('元ヘッダー名の対応だけを保存しました。定数や行データは含みません。','Saved only source-header mappings. No constants or row data included.');}catch(e){show(e);}};
$('recipe-load').onchange=async()=>{const f=$('recipe-load').files[0],token=epoch;if(!f)return;try{if(!rows.length)throw Error(t('先に今回のCSVの列を読み取ってください。','Read the current CSV columns first.'));if(f.size>32768)throw Error('recipeSize');const candidate=M.readRecipe(await f.text(),rows[0]);if(token!==epoch)return;for(const c of M.columns)$('map-'+c).value=candidate[c]||'';resetConstants();for(const c of M.columns)update(c);$('error').textContent=t('対応を読み込みました。今回の定数と金額の意味を確認してください。','Mappings loaded. Reconfirm constants and amount meanings for this file.');}catch(e){if(token===epoch)show(e);}finally{$('recipe-load').value='';}};
}
